//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TowerDefenseInput
{
    public partial class @GameInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""ba74c39c-9bc4-44b0-b528-c269b4537aa9"",
            ""actions"": [
                {
                    ""name"": ""CameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""ff740347-9c58-471c-9bbb-12beeebe2dca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraRotate"",
                    ""type"": ""Value"",
                    ""id"": ""c2654ce5-136a-4a84-9a6c-3ff1a8aaed4f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""aa0ab78f-3af8-4756-ac27-bbf968be0047"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""9bdbdafb-f876-422a-a990-140594028adf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectTower"",
                    ""type"": ""Button"",
                    ""id"": ""8c2c2d58-f6f7-497d-b021-ab8129ee3307"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""36e24a10-e0f9-4152-9b71-f2d915461a2d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""ebe4f181-11b7-4a0f-aae4-707fcddd9dc1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""6fee32bb-f9d4-42ac-b5b4-4ec809d415d0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""85c462cb-0dc1-48ed-894e-e8fccc2f3708"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""e36fc4db-7166-4a97-8958-1ac3067ad58b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a23d2e96-16a3-4066-91c4-d010104e4f2b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b155eb3c-5514-4199-951d-cf7ba7f6b8d6"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""fe29ec8f-4b6d-4e22-8005-275d670efee8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraRotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""af8dedc9-4528-456b-b78e-49a425c30c23"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba8e3eda-c260-4d81-9202-408814cff7df"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1508c37-2e94-4a00-9807-3fd59a844f0e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""b4cc9d02-b1b9-4df0-a4f4-a32a49462b08"",
            ""actions"": [
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""a9acbcc2-e96e-4233-a627-4c9c8708f54b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8c06e28-d08e-4926-bc72-cb89ba36ef2f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BuildMode"",
            ""id"": ""0f71615b-1c7f-4e8a-a5f3-a537af2d0ff5"",
            ""actions"": [
                {
                    ""name"": ""BuildTower"",
                    ""type"": ""Button"",
                    ""id"": ""aae39e56-d50d-47eb-a76a-69116ad0ccdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildCancel"",
                    ""type"": ""Button"",
                    ""id"": ""50023439-416e-4f80-b855-8f8628ffe315"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""449c402c-c879-465d-9874-ca7050c24916"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildTower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0abb62e5-3d20-4979-b461-d450585f2a66"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""EditMode"",
            ""id"": ""d3018488-04c1-4530-a8a6-13d5fb86d30c"",
            ""actions"": [
                {
                    ""name"": ""SelectTower"",
                    ""type"": ""Button"",
                    ""id"": ""61c78dd6-b78f-4f51-948b-c0a4ad94f3cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectCancel"",
                    ""type"": ""Button"",
                    ""id"": ""bb94de50-ba27-4547-87f6-bf9ef1377767"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1c4ef0e-67e0-4111-ad81-f28ee583e236"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectTower"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff3ca109-2592-44f6-9cc7-52034ec61b06"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GamePlay
            m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
            m_GamePlay_CameraMove = m_GamePlay.FindAction("CameraMove", throwIfNotFound: true);
            m_GamePlay_CameraRotate = m_GamePlay.FindAction("CameraRotate", throwIfNotFound: true);
            m_GamePlay_CursorPosition = m_GamePlay.FindAction("CursorPosition", throwIfNotFound: true);
            m_GamePlay_Pause = m_GamePlay.FindAction("Pause", throwIfNotFound: true);
            m_GamePlay_SelectTower = m_GamePlay.FindAction("SelectTower", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Resume = m_UI.FindAction("Resume", throwIfNotFound: true);
            // BuildMode
            m_BuildMode = asset.FindActionMap("BuildMode", throwIfNotFound: true);
            m_BuildMode_BuildTower = m_BuildMode.FindAction("BuildTower", throwIfNotFound: true);
            m_BuildMode_BuildCancel = m_BuildMode.FindAction("BuildCancel", throwIfNotFound: true);
            // EditMode
            m_EditMode = asset.FindActionMap("EditMode", throwIfNotFound: true);
            m_EditMode_SelectTower = m_EditMode.FindAction("SelectTower", throwIfNotFound: true);
            m_EditMode_SelectCancel = m_EditMode.FindAction("SelectCancel", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GamePlay
        private readonly InputActionMap m_GamePlay;
        private IGamePlayActions m_GamePlayActionsCallbackInterface;
        private readonly InputAction m_GamePlay_CameraMove;
        private readonly InputAction m_GamePlay_CameraRotate;
        private readonly InputAction m_GamePlay_CursorPosition;
        private readonly InputAction m_GamePlay_Pause;
        private readonly InputAction m_GamePlay_SelectTower;
        public struct GamePlayActions
        {
            private @GameInput m_Wrapper;
            public GamePlayActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @CameraMove => m_Wrapper.m_GamePlay_CameraMove;
            public InputAction @CameraRotate => m_Wrapper.m_GamePlay_CameraRotate;
            public InputAction @CursorPosition => m_Wrapper.m_GamePlay_CursorPosition;
            public InputAction @Pause => m_Wrapper.m_GamePlay_Pause;
            public InputAction @SelectTower => m_Wrapper.m_GamePlay_SelectTower;
            public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
            public void SetCallbacks(IGamePlayActions instance)
            {
                if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
                {
                    @CameraMove.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraMove;
                    @CameraMove.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraMove;
                    @CameraMove.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraMove;
                    @CameraRotate.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraRotate;
                    @CameraRotate.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraRotate;
                    @CameraRotate.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCameraRotate;
                    @CursorPosition.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCursorPosition;
                    @CursorPosition.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCursorPosition;
                    @CursorPosition.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnCursorPosition;
                    @Pause.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                    @Pause.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                    @Pause.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnPause;
                    @SelectTower.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectTower;
                    @SelectTower.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectTower;
                    @SelectTower.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnSelectTower;
                }
                m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @CameraMove.started += instance.OnCameraMove;
                    @CameraMove.performed += instance.OnCameraMove;
                    @CameraMove.canceled += instance.OnCameraMove;
                    @CameraRotate.started += instance.OnCameraRotate;
                    @CameraRotate.performed += instance.OnCameraRotate;
                    @CameraRotate.canceled += instance.OnCameraRotate;
                    @CursorPosition.started += instance.OnCursorPosition;
                    @CursorPosition.performed += instance.OnCursorPosition;
                    @CursorPosition.canceled += instance.OnCursorPosition;
                    @Pause.started += instance.OnPause;
                    @Pause.performed += instance.OnPause;
                    @Pause.canceled += instance.OnPause;
                    @SelectTower.started += instance.OnSelectTower;
                    @SelectTower.performed += instance.OnSelectTower;
                    @SelectTower.canceled += instance.OnSelectTower;
                }
            }
        }
        public GamePlayActions @GamePlay => new GamePlayActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        private readonly InputAction m_UI_Resume;
        public struct UIActions
        {
            private @GameInput m_Wrapper;
            public UIActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Resume => m_Wrapper.m_UI_Resume;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                    @Resume.started -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                    @Resume.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                    @Resume.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnResume;
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Resume.started += instance.OnResume;
                    @Resume.performed += instance.OnResume;
                    @Resume.canceled += instance.OnResume;
                }
            }
        }
        public UIActions @UI => new UIActions(this);

        // BuildMode
        private readonly InputActionMap m_BuildMode;
        private IBuildModeActions m_BuildModeActionsCallbackInterface;
        private readonly InputAction m_BuildMode_BuildTower;
        private readonly InputAction m_BuildMode_BuildCancel;
        public struct BuildModeActions
        {
            private @GameInput m_Wrapper;
            public BuildModeActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @BuildTower => m_Wrapper.m_BuildMode_BuildTower;
            public InputAction @BuildCancel => m_Wrapper.m_BuildMode_BuildCancel;
            public InputActionMap Get() { return m_Wrapper.m_BuildMode; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BuildModeActions set) { return set.Get(); }
            public void SetCallbacks(IBuildModeActions instance)
            {
                if (m_Wrapper.m_BuildModeActionsCallbackInterface != null)
                {
                    @BuildTower.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildTower;
                    @BuildTower.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildTower;
                    @BuildTower.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildTower;
                    @BuildCancel.started -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildCancel;
                    @BuildCancel.performed -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildCancel;
                    @BuildCancel.canceled -= m_Wrapper.m_BuildModeActionsCallbackInterface.OnBuildCancel;
                }
                m_Wrapper.m_BuildModeActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @BuildTower.started += instance.OnBuildTower;
                    @BuildTower.performed += instance.OnBuildTower;
                    @BuildTower.canceled += instance.OnBuildTower;
                    @BuildCancel.started += instance.OnBuildCancel;
                    @BuildCancel.performed += instance.OnBuildCancel;
                    @BuildCancel.canceled += instance.OnBuildCancel;
                }
            }
        }
        public BuildModeActions @BuildMode => new BuildModeActions(this);

        // EditMode
        private readonly InputActionMap m_EditMode;
        private IEditModeActions m_EditModeActionsCallbackInterface;
        private readonly InputAction m_EditMode_SelectTower;
        private readonly InputAction m_EditMode_SelectCancel;
        public struct EditModeActions
        {
            private @GameInput m_Wrapper;
            public EditModeActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @SelectTower => m_Wrapper.m_EditMode_SelectTower;
            public InputAction @SelectCancel => m_Wrapper.m_EditMode_SelectCancel;
            public InputActionMap Get() { return m_Wrapper.m_EditMode; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(EditModeActions set) { return set.Get(); }
            public void SetCallbacks(IEditModeActions instance)
            {
                if (m_Wrapper.m_EditModeActionsCallbackInterface != null)
                {
                    @SelectTower.started -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectTower;
                    @SelectTower.performed -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectTower;
                    @SelectTower.canceled -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectTower;
                    @SelectCancel.started -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectCancel;
                    @SelectCancel.performed -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectCancel;
                    @SelectCancel.canceled -= m_Wrapper.m_EditModeActionsCallbackInterface.OnSelectCancel;
                }
                m_Wrapper.m_EditModeActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @SelectTower.started += instance.OnSelectTower;
                    @SelectTower.performed += instance.OnSelectTower;
                    @SelectTower.canceled += instance.OnSelectTower;
                    @SelectCancel.started += instance.OnSelectCancel;
                    @SelectCancel.performed += instance.OnSelectCancel;
                    @SelectCancel.canceled += instance.OnSelectCancel;
                }
            }
        }
        public EditModeActions @EditMode => new EditModeActions(this);
        public interface IGamePlayActions
        {
            void OnCameraMove(InputAction.CallbackContext context);
            void OnCameraRotate(InputAction.CallbackContext context);
            void OnCursorPosition(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnSelectTower(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnResume(InputAction.CallbackContext context);
        }
        public interface IBuildModeActions
        {
            void OnBuildTower(InputAction.CallbackContext context);
            void OnBuildCancel(InputAction.CallbackContext context);
        }
        public interface IEditModeActions
        {
            void OnSelectTower(InputAction.CallbackContext context);
            void OnSelectCancel(InputAction.CallbackContext context);
        }
    }
}
